chore(deps): update rust crate object_store to v0.12.4 (#4731)
Coming soon: The Renovate bot (GitHub App) will be renamed to Mend. PRs
from Renovate will soon appear from 'Mend'. Learn more
[here](https://redirect.github.com/renovatebot/renovate/discussions/37842).

This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
|
[object_store](https://redirect.github.com/apache/arrow-rs-object-store)
| workspace.dependencies | patch | `0.12.3` -> `0.12.4` |

---

### Release Notes

<details>
<summary>apache/arrow-rs-object-store (object_store)</summary>

###
[`v0.12.4`](https://redirect.github.com/apache/arrow-rs-object-store/blob/HEAD/CHANGELOG.md#v0124-2025-09-19)

[Compare
Source](https://redirect.github.com/apache/arrow-rs-object-store/compare/v0.12.3...v0.12.4)

[Full
Changelog](https://redirect.github.com/apache/arrow-rs-object-store/compare/v0.12.3...v0.12.4)

**Implemented enhancements:**

- Allow flagging `PUT` operations as idempotent.
[#&#8203;464](https://redirect.github.com/apache/arrow-rs-object-store/issues/464)
- Release object store `0.12.3` (non breaking API) Release July 2025
[#&#8203;428](https://redirect.github.com/apache/arrow-rs-object-store/issues/428)
- LocalFileSystem: offset for `list_with_offset` can't be identified /
List results \*must\* be sorted
[#&#8203;388](https://redirect.github.com/apache/arrow-rs-object-store/issues/388)
- Support setting storage class when objects are written
[#&#8203;330](https://redirect.github.com/apache/arrow-rs-object-store/issues/330)
- Support auth using AssumeRoleWithWebIdentity for non-AWS S3-compatible
implementations
[#&#8203;283](https://redirect.github.com/apache/arrow-rs-object-store/issues/283)
- Types from http through request leak into object\_store public
interfaces but aren't re-exported
[#&#8203;263](https://redirect.github.com/apache/arrow-rs-object-store/issues/263)

**Fixed bugs:**

- Retry does not cover connection errors
[#&#8203;368](https://redirect.github.com/apache/arrow-rs-object-store/issues/368)

**Documentation updates:**

- Improve documentation for http client timeout
[#&#8203;390](https://redirect.github.com/apache/arrow-rs-object-store/pull/390)
([alamb](https://redirect.github.com/alamb))

**Closed issues:**

- When a client http request is retried, I would like more information
in the `info!` about the retry
[#&#8203;486](https://redirect.github.com/apache/arrow-rs-object-store/issues/486)
- Range header causing AWS Signature issues
[#&#8203;471](https://redirect.github.com/apache/arrow-rs-object-store/issues/471)
- Impossible to downcast an Error::Generic into a RetryError
[#&#8203;469](https://redirect.github.com/apache/arrow-rs-object-store/issues/469)
- JWT session tokens cause SignatureDoesNotMatch with Supabase S3
[#&#8203;466](https://redirect.github.com/apache/arrow-rs-object-store/issues/466)
- Double url-encoding of special characters in key names
[#&#8203;457](https://redirect.github.com/apache/arrow-rs-object-store/issues/457)
- Make `MultipartUpload` Sync
[#&#8203;439](https://redirect.github.com/apache/arrow-rs-object-store/issues/439)
- Integrate HDFS object store
[#&#8203;424](https://redirect.github.com/apache/arrow-rs-object-store/issues/424)
- Error performing POST when trying to write to S3 with a custom
endpoint URL
[#&#8203;408](https://redirect.github.com/apache/arrow-rs-object-store/issues/408)

**Merged pull requests:**

- Revert "refactor: remove AWS dynamo integration
([#&#8203;407](https://redirect.github.com/apache/arrow-rs-object-store/issues/407))"
[#&#8203;493](https://redirect.github.com/apache/arrow-rs-object-store/pull/493)
([alamb](https://redirect.github.com/alamb))
- Fix for clippy 1.90
[#&#8203;492](https://redirect.github.com/apache/arrow-rs-object-store/pull/492)
([alamb](https://redirect.github.com/alamb))
- Add version 0.12.4 release plan to README
[#&#8203;490](https://redirect.github.com/apache/arrow-rs-object-store/pull/490)
([alamb](https://redirect.github.com/alamb))
- chore(client/retry): include error info in logs when retry occurs
[#&#8203;487](https://redirect.github.com/apache/arrow-rs-object-store/pull/487)
([philjb](https://redirect.github.com/philjb))
- AWS S3: Support STS endpoint, WebIdentity, RoleArn, RoleSession
configuration
[#&#8203;480](https://redirect.github.com/apache/arrow-rs-object-store/pull/480)
([Friede80](https://redirect.github.com/Friede80))
- build(deps): bump actions/github-script from 7 to 8
[#&#8203;478](https://redirect.github.com/apache/arrow-rs-object-store/pull/478)
([dependabot\[bot\]](https://redirect.github.com/apps/dependabot))
- build(deps): bump actions/setup-node from 4 to 5
[#&#8203;477](https://redirect.github.com/apache/arrow-rs-object-store/pull/477)
([dependabot\[bot\]](https://redirect.github.com/apps/dependabot))
- build(deps): bump actions/setup-python from 5 to 6
[#&#8203;476](https://redirect.github.com/apache/arrow-rs-object-store/pull/476)
([dependabot\[bot\]](https://redirect.github.com/apps/dependabot))
- chore: fix some clippy 1.89 warnings and ignore some doctests on
wasm32
[#&#8203;468](https://redirect.github.com/apache/arrow-rs-object-store/pull/468)
([mbrobbel](https://redirect.github.com/mbrobbel))
- Allow "application\_credentials" in `impl FromStr for GoogleConfigKey`
[#&#8203;467](https://redirect.github.com/apache/arrow-rs-object-store/pull/467)
([kylebarron](https://redirect.github.com/kylebarron))
- build(deps): bump actions/checkout from 4 to 5
[#&#8203;463](https://redirect.github.com/apache/arrow-rs-object-store/pull/463)
([dependabot\[bot\]](https://redirect.github.com/apps/dependabot))
- Add storage class for aws, gcp, and azure
[#&#8203;456](https://redirect.github.com/apache/arrow-rs-object-store/pull/456)
([matthewmturner](https://redirect.github.com/matthewmturner))
- Remove use of deprecated StepRng from tests
[#&#8203;449](https://redirect.github.com/apache/arrow-rs-object-store/pull/449)
([tustvold](https://redirect.github.com/tustvold))
- Fix not retrying connection errors
[#&#8203;445](https://redirect.github.com/apache/arrow-rs-object-store/pull/445)
([johnnyg](https://redirect.github.com/johnnyg))
- Dont unwrap on body send
[#&#8203;442](https://redirect.github.com/apache/arrow-rs-object-store/pull/442)
([cetra3](https://redirect.github.com/cetra3))
- feat: re-export HTTP types used in public API
[#&#8203;441](https://redirect.github.com/apache/arrow-rs-object-store/pull/441)
([ByteBaker](https://redirect.github.com/ByteBaker))
- fix: update links in release docs and script
[#&#8203;440](https://redirect.github.com/apache/arrow-rs-object-store/pull/440)
([mbrobbel](https://redirect.github.com/mbrobbel))
- chore: prepare `0.12.3` release
[#&#8203;437](https://redirect.github.com/apache/arrow-rs-object-store/pull/437)
([crepererum](https://redirect.github.com/crepererum))
- aws: downgrade credential provider info! log messages to debug!
[#&#8203;436](https://redirect.github.com/apache/arrow-rs-object-store/pull/436)
([asubiotto](https://redirect.github.com/asubiotto))
- feat: retry on 408
[#&#8203;426](https://redirect.github.com/apache/arrow-rs-object-store/pull/426)
([criccomini](https://redirect.github.com/criccomini))
- fix: expose source of `RetryError`
[#&#8203;422](https://redirect.github.com/apache/arrow-rs-object-store/pull/422)
([crepererum](https://redirect.github.com/crepererum))
- fix(gcp): throw error instead of panicking if read pem fails
[#&#8203;421](https://redirect.github.com/apache/arrow-rs-object-store/pull/421)
([hugocasa](https://redirect.github.com/hugocasa))
- chore: fix clippy 1.88 warnings
[#&#8203;418](https://redirect.github.com/apache/arrow-rs-object-store/pull/418)
([mbrobbel](https://redirect.github.com/mbrobbel))
- Bump quick-xml to version 0.38.0
[#&#8203;417](https://redirect.github.com/apache/arrow-rs-object-store/pull/417)
([raimannma](https://redirect.github.com/raimannma))
- Prevent compilation error with all cloud features but fs turned on
[#&#8203;412](https://redirect.github.com/apache/arrow-rs-object-store/pull/412)
([jder](https://redirect.github.com/jder))
- Retry requests when status code is 429
[#&#8203;410](https://redirect.github.com/apache/arrow-rs-object-store/pull/410)
([paraseba](https://redirect.github.com/paraseba))
- refactor: remove AWS dynamo integration
[#&#8203;407](https://redirect.github.com/apache/arrow-rs-object-store/pull/407)
([crepererum](https://redirect.github.com/crepererum))
- refactor: `PutMultiPartOpts` => `PutMultiPartOptions`
[#&#8203;406](https://redirect.github.com/apache/arrow-rs-object-store/pull/406)
([crepererum](https://redirect.github.com/crepererum))
- minor: Pin `tracing-attributes`, `tracing-core` to fix CI
[#&#8203;404](https://redirect.github.com/apache/arrow-rs-object-store/pull/404)
([kylebarron](https://redirect.github.com/kylebarron))
- feat (azure): support for account in `az://` URLs
[#&#8203;403](https://redirect.github.com/apache/arrow-rs-object-store/pull/403)
([ByteBaker](https://redirect.github.com/ByteBaker))
- Fix azure path parsing
[#&#8203;399](https://redirect.github.com/apache/arrow-rs-object-store/pull/399)
([kylebarron](https://redirect.github.com/kylebarron))

\* *This Changelog was automatically generated by
[github\_changelog\_generator](https://redirect.github.com/github-changelog-generator/github-changelog-generator)*

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update
again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/vortex-data/vortex).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiI0MS45Ny4xMCIsInVwZGF0ZWRJblZlciI6IjQxLjk3LjEwIiwidGFyZ2V0QnJhbmNoIjoiZGV2ZWxvcCIsImxhYmVscyI6WyJjaG9yZSJdfQ==-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>